package organized.chaos;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * Panel para la carga del archivo de texto
 * @author Andres, Michelle
 */
public class LoadPanel extends javax.swing.JPanel {

    private File selectedFile;

    /**
     * Creates new form LoadPanel
     */
    public LoadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooser = new javax.swing.JFileChooser();
        titleLabel = new javax.swing.JLabel();
        chooseButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setForeground(java.awt.Color.black);
        titleLabel.setText("¡Bienvenidos al Sistema de Distribución de Amazon!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(titleLabel, gridBagConstraints);

        chooseButton.setBackground(new java.awt.Color(255, 204, 51));
        chooseButton.setForeground(java.awt.Color.black);
        chooseButton.setText("Seleccionar archivo...");
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(chooseButton, gridBagConstraints);

        loadButton.setBackground(new java.awt.Color(255, 204, 51));
        loadButton.setForeground(java.awt.Color.black);
        loadButton.setText("Cargar datos");
        loadButton.setEnabled(false);
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(loadButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Botón para seleccionar el archivo de texto
     * @param evt 
     */
    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            loadButton.setEnabled(true);
        }
    }//GEN-LAST:event_chooseButtonActionPerformed

    /**
     * Botón para cargar el archivo de texto
     * @param evt 
     */
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        if (selectedFile != null) {
            App.getInstance().loadFile(selectedFile);
        }
        App.getInstance().showOptionsPanel();
    }//GEN-LAST:event_loadButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseButton;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
